server {
    listen 80;
    server_name 47.108.145.203;

    location / {
        root /opt/wps-baixiaosheng/frontend/dist;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control no-cache;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8099;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }
}
